### PR TITLE
Check the value of event.button only if mouseButton is explicitely sp…

### PR DESCRIPTION
**Pull request by julienw**
…ecified

Fixes https://github.com/firefox-devtools/profiler/issues/3453

### CODE REVIEW

**Comment by julienw** [comment]
@mstange can you please double-check this works for you locally ?
Using `yarn link` in this repository, and `yarn link react-contextmenu` in the profiler's repository, and then testing ctrl+click on Mac?

**Comment by mstange** [comment]
> @mstange can you please double-check this works for you locally ?
> Using `yarn link` in this repository, and `yarn link react-contextmenu` in the profiler's repository, and then testing ctrl+click on Mac?

I tried this but `yarn start` then prints `Module not found: Error: Can't resolve 'react-contextmenu' in '/Users/mstange/code/perf.html/src/components/shared'`

**Comment by mstange** [comment]
The problem was that I hadn't run `yarn && yarn build` in the react-contextmenu directory.

**Review by mstange — APPROVED** [review]
This works but I'm not sure if it's the best API. Specifically, combining a contextmenu listener with a button check seems like something that should be avoided at the API level. I think the user should need to make the choice between: 1. contextmenu event (no check), 2. mousedown event with optional button check, or 3. click event with optional button check.

But this change definitely gets us unblocked and seems fine on its own.

**Comment by mstange** [comment]
Even with this change, the call tree context menu doesn't display with ctrl+click in the profiler, but that has a different reason - we don't set the right clicked node in response to ctrl+clicks, so CallNodeContextMenu doesn't render a ContextMenu.

**Comment by julienw** [comment]
> This works but I'm not sure if it's the best API. Specifically, combining a contextmenu listener with a button check seems like something that should be avoided at the API level. I think the user should need to make the choice between: 1. contextmenu event (no check), 2. mousedown event with optional button check, or 3. click event with optional button check.

Yes, I find it also a bit weird that we listen to both the `click` and `contextmenu` events. I think you're right. But I also don't want to do too much changes to this lib :-)

**Pull request merged**
